### ISSUE TITLE
Add a function to grab question answers from a stackexchange domain

### ISSUE THREAD

**Issue by AndrewFM** [AndrewFM/NLPFinal#3]
The API has the ability to provide a search query, and it'll return questions that match that query. I think I also saw that it has another function called 'similar', which I think returns questions that are similar to a query. Maybe we want to use that instead of search.

We'll probably grab the top 5 or 10 results to work with, I guess. Also will probably only hold on to the highest-voted/accepted answer from each question.

**Comment by MoonWatcher582** [comment]
Grabs 5 similar questions/domain and returns a list of accepted answers; left in html format for now

**Comment by MoonWatcher582** [comment]
TODO: use beautifulsoup to parse out the html.

**Comment by MoonWatcher582** [comment]
HTML parser added
